# Generated by Django 5.2.12 on 2026-04-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthosApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethos_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('about', models.JSONField(default=list)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EthosResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ethos.ethosapplication')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EthosRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_media_type', models.CharField(max_length=300)),
                ('methods', models.JSONField(default=list)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('filters', models.JSONField(default=list)),
                ('deprecation_notice', models.JSONField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='ethos.ethosresource')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
