# Generated by Django 5.2.12 on 2026-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(db_index=True, max_length=500)),
                ('message_type', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(db_index=True, null=True)),
                ('response_body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_on'],
            },
        ),
    ]
