# Generated by Django 5.2.17 on 2026-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethos', '0003_resource_preferred_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthosConsumeCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_id', models.BigIntegerField(default=0)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EthosMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.BigIntegerField(db_index=True)),
                ('published_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resource_name', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(db_index=True, max_length=64)),
                ('resource_version', models.CharField(blank=True, max_length=200)),
                ('operation', models.CharField(db_index=True, max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('message_type', models.CharField(blank=True, max_length=50)),
                ('sis_message_id', models.CharField(blank=True, max_length=50)),
                ('initiated_on', models.DateTimeField(blank=True, null=True)),
                ('publisher_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=10)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('action_detail', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_pk', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-queue_id'],
                'indexes': [models.Index(fields=['resource_name', 'status'], name='ethos_ethos_resourc_3430d6_idx')],
            },
        ),
    ]
