# Generated by Django 5.2.17 on 2026-10-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '__first__'),
        ('ethos', '0005_menu_ethos_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethosapplication',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cis.campus'),
        ),
        migrations.AddField(
            model_name='ethosconsumecursor',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cis.campus'),
        ),
        migrations.AddField(
            model_name='ethoslog',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cis.campus'),
        ),
        migrations.AddField(
            model_name='ethosmessage',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cis.campus'),
        ),
        migrations.AlterField(
            model_name='ethosapplication',
            name='ethos_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ethosapplication',
            constraint=models.UniqueConstraint(fields=('campus', 'ethos_id'), name='ethosapp_campus_ethos_id'),
        ),
        migrations.AddConstraint(
            model_name='ethosapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('ethos_id',), name='ethosapp_ethos_id_no_campus'),
        ),
        migrations.AddConstraint(
            model_name='ethosconsumecursor',
            constraint=models.UniqueConstraint(fields=('campus',), name='ethoscursor_campus'),
        ),
    ]
